// Page-specific color themes for visual distinction

export const pageThemes = {
  dashboard: {
    name: 'Dashboard',
    gradient: 'from-indigo-500 to-purple-600',
    bg: 'bg-indigo-50',
    border: 'border-indigo-200',
    text: 'text-indigo-900',
    accent: 'text-indigo-600',
    button: 'bg-indigo-600 hover:bg-indigo-700',
    card: 'bg-white border-indigo-100',
    badge: 'bg-indigo-100 text-indigo-700',
  },
  employees: {
    name: 'Employees',
    gradient: 'from-blue-500 to-cyan-600',
    bg: 'bg-blue-50',
    border: 'border-blue-200',
    text: 'text-blue-900',
    accent: 'text-blue-600',
    button: 'bg-blue-600 hover:bg-blue-700',
    card: 'bg-white border-blue-100',
    badge: 'bg-blue-100 text-blue-700',
  },
  attendance: {
    name: 'Attendance',
    gradient: 'from-emerald-500 to-teal-600',
    bg: 'bg-emerald-50',
    border: 'border-emerald-200',
    text: 'text-emerald-900',
    accent: 'text-emerald-600',
    button: 'bg-emerald-600 hover:bg-emerald-700',
    card: 'bg-white border-emerald-100',
    badge: 'bg-emerald-100 text-emerald-700',
  },
  leave: {
    name: 'Leave Management',
    gradient: 'from-amber-500 to-orange-600',
    bg: 'bg-amber-50',
    border: 'border-amber-200',
    text: 'text-amber-900',
    accent: 'text-amber-600',
    button: 'bg-amber-600 hover:bg-amber-700',
    card: 'bg-white border-amber-100',
    badge: 'bg-amber-100 text-amber-700',
  },
  payroll: {
    name: 'Payroll',
    gradient: 'from-green-500 to-emerald-600',
    bg: 'bg-green-50',
    border: 'border-green-200',
    text: 'text-green-900',
    accent: 'text-green-600',
    button: 'bg-green-600 hover:bg-green-700',
    card: 'bg-white border-green-100',
    badge: 'bg-green-100 text-green-700',
  },
  reports: {
    name: 'Reports',
    gradient: 'from-purple-500 to-pink-600',
    bg: 'bg-purple-50',
    border: 'border-purple-200',
    text: 'text-purple-900',
    accent: 'text-purple-600',
    button: 'bg-purple-600 hover:bg-purple-700',
    card: 'bg-white border-purple-100',
    badge: 'bg-purple-100 text-purple-700',
  },
  departments: {
    name: 'Departments',
    gradient: 'from-rose-500 to-pink-600',
    bg: 'bg-rose-50',
    border: 'border-rose-200',
    text: 'text-rose-900',
    accent: 'text-rose-600',
    button: 'bg-rose-600 hover:bg-rose-700',
    card: 'bg-white border-rose-100',
    badge: 'bg-rose-100 text-rose-700',
  },
  holidays: {
    name: 'Holidays',
    gradient: 'from-sky-500 to-blue-600',
    bg: 'bg-sky-50',
    border: 'border-sky-200',
    text: 'text-sky-900',
    accent: 'text-sky-600',
    button: 'bg-sky-600 hover:bg-sky-700',
    card: 'bg-white border-sky-100',
    badge: 'bg-sky-100 text-sky-700',
  },
  settings: {
    name: 'Settings',
    gradient: 'from-slate-500 to-gray-600',
    bg: 'bg-slate-50',
    border: 'border-slate-200',
    text: 'text-slate-900',
    accent: 'text-slate-600',
    button: 'bg-slate-600 hover:bg-slate-700',
    card: 'bg-white border-slate-100',
    badge: 'bg-slate-100 text-slate-700',
  },
  profile: {
    name: 'Profile',
    gradient: 'from-violet-500 to-purple-600',
    bg: 'bg-violet-50',
    border: 'border-violet-200',
    text: 'text-violet-900',
    accent: 'text-violet-600',
    button: 'bg-violet-600 hover:bg-violet-700',
    card: 'bg-white border-violet-100',
    badge: 'bg-violet-100 text-violet-700',
  },
  announcements: {
    name: 'Announcements',
    gradient: 'from-fuchsia-500 to-pink-600',
    bg: 'bg-fuchsia-50',
    border: 'border-fuchsia-200',
    text: 'text-fuchsia-900',
    accent: 'text-fuchsia-600',
    button: 'bg-fuchsia-600 hover:bg-fuchsia-700',
    card: 'bg-white border-fuchsia-100',
    badge: 'bg-fuchsia-100 text-fuchsia-700',
  },
} as const;

export type PageThemeKey = keyof typeof pageThemes;

export function getPageTheme(page: PageThemeKey) {
  return pageThemes[page];
}
